# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bac21cff7eabf46fbc270b48e5f2525daea1310f93691d4cfca9b5cd706efdaea073871702c1eabc5caa4ac7b11063be886d80387b266e13ecd2ffc57070458

test:
  secret_key_base: 6d8a892f7f6301315e20c06cf58c924d489f5ce8d583f6a4c5f16f3ed7184becd53ad8ccb83401144f4fa97ed894175bd1cd051088325c2c70fcaa2e7266b66d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
